In [1]:
import numpy as np

In [2]:
constant=np.array([2])

In [4]:
vector=np.array([2,3,5,6])

In [5]:
matrix=np.array([[2,4,5],[3,6,3],[2,3,5]])

In [6]:
tensor=np.array([[[2,4,5],[3,6,3],[2,3,5]],[[2,4,5],[3,6,3],[2,3,5]]])

In [7]:
constant

array([2])

In [8]:
vector

array([2, 3, 5, 6])

In [9]:
matrix

array([[2, 4, 5],
       [3, 6, 3],
       [2, 3, 5]])

In [10]:
tensor

array([[[2, 4, 5],
        [3, 6, 3],
        [2, 3, 5]],

       [[2, 4, 5],
        [3, 6, 3],
        [2, 3, 5]]])

In [11]:
constant.shape

(1,)

In [12]:
vector.shape

(4,)

In [13]:
matrix.shape

(3, 3)

In [14]:
tensor.shape

(2, 3, 3)